version: '3.9'
services:
  frontend:
    build: ./front-end/
    ports:
      - 5173:5173
    environment:
      - REACT_APP_HOSTNAME=database
      - REACT_APP_BACKEND_PORT=3001
    platform: linux/x86_64
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5

  backend:
    build: ./back-end/
    ports:
      - 3001:3001
    depends_on: 
      database:
        condition: service_healthy
    environment:
      PORT: 3001
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGDATABASE: ngcash_api
      PGHOST: database
      API_PORT: 3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  database:
    image: postgres
    platform: linux/x86_64
    container_name: database
    ports:
      - 5430:5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE
    
